# Generated by Django 5.0.1 on 2024-01-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniap', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='mood',
        ),
    ]
